/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        /**
         * Put Config
         * @description Persist changes and refresh the in-memory Config.
         *
         *     Body shape mirrors GET; any field omitted is left untouched.
         *     Including `secrets` (dict[str, str]) writes those KEY=VALUE pairs
         *     to config/secrets.env and updates os.environ for the live process.
         */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Round-trip `complete('ping')` against each LLM endpoint and
         *     return per-role status (ok/detail). Costs at most a tiny number of
         *     tokens per role.
         */
        post: operations["validate_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_papers_get"];
        put?: never;
        /**
         * Upload Paper
         * @description Accept a PDF upload, register it, return the new paper_id.
         *
         *     Mirrors `papercast scan` for one file: stream to inbox, hash, copy
         *     into work/<pid>/source.pdf, insert DB row, move original to archive.
         */
        post: operations["upload_paper_api_papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Paper
         * @description Hard delete: drop work/<pid>/, review/<pid>/, and the DB row.
         *
         *     output/<filename>.mp4 is intentionally NOT removed — that's the
         *     final deliverable and the user may still want it.
         */
        delete: operations["delete_paper_api_papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Inbox Route
         * @description Trigger a full inbox scan (covers PDFs already on disk before the
         *     server started). Equivalent to `papercast scan`.
         */
        post: operations["scan_inbox_route_api_papers_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Paper
         * @description Kick off the JobOrchestrator for this paper.
         */
        post: operations["start_paper_api_papers__paper_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Paper */
        post: operations["stop_paper_api_papers__paper_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Paper
         * @description If the paper is in `failed`, walk back to its previous successful
         *     stage. Mirrors `papercast retry-failed` for one paper.
         */
        post: operations["retry_paper_api_papers__paper_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Paper Artifacts
         * @description List logical artifact names that exist on disk for this paper.
         */
        get: operations["list_paper_artifacts_api_papers__paper_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/artifact/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Stream a binary artifact, or wrap a text artifact in JSON.
         *
         *     Returns:
         *         - FileResponse for binary types (.pdf, .pptx, .mp4, .png, .mp3)
         *         - TextArtifactResponse for textual types (.json, .md, ...)
         */
        get: operations["get_artifact_api_papers__paper_id__artifact__name__get"];
        /**
         * Put Artifact Text
         * @description Overwrite a text artifact with the request body.
         *
         *     Only artifacts in WRITABLE_ARTIFACTS are accepted; everything else
         *     is read-only via this endpoint. Binary replacements go through
         *     POST /artifact/{name}/upload.
         */
        put: operations["put_artifact_text_api_papers__paper_id__artifact__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/artifact/{name}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Artifact Binary
         * @description Replace a binary artifact (currently: pptx). Reviewer downloads
         *     the auto-generated .pptx, edits in PowerPoint, drops the new file
         *     here to overwrite.
         */
        post: operations["post_artifact_binary_api_papers__paper_id__artifact__name__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Roots
         * @description Available root names. The WebUI uses this to populate the file
         *     tree's top level.
         */
        get: operations["list_roots_api_files_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_files_get"];
        put?: never;
        post?: never;
        /** Delete Path */
        delete: operations["delete_path_api_files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Download a single file. Used by the WebUI for cases where a
         *     direct link to the file is more useful than the artifact wrapper
         *     (e.g. re-downloading the .pptx for local editing).
         */
        get: operations["download_file_api_files_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description General-purpose upload to a whitelisted root.
         *
         *     Currently restricted to `inbox` to avoid polluting work/review/output
         *     with arbitrary user files. The proper way to insert a paper is via
         *     POST /api/papers (which calls inbox upload + scan internally), but
         *     this endpoint is handy for batch ingest.
         */
        post: operations["upload_api_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal In Explorer
         * @description Open the OS file manager focused on the file. Best-effort —
         *     headless servers / different desktop environments may no-op.
         */
        post: operations["reveal_in_explorer_api_files_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_papers__paper_id__review_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_papers__paper_id__review_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/regenerate/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Preview
         * @description Render the LLM prompt that *would* be sent for this regenerate
         *     request, without actually calling the LLM. Useful for the WebUI to
         *     let the reviewer eyeball / tweak the request before spending tokens.
         */
        post: operations["regenerate_preview_api_papers__paper_id__review_regenerate_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Report Date
             * @description Date string substituted into Cover's {{REPORT_DATE}}; any format the lab template accepts (e.g. '2026年5月17日').
             */
            report_date?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /**
             * Voice
             * @description MiniMax voice_id (overrides config tts.voice for this paper).
             */
            voice?: string | null;
            /** Overrides */
            overrides?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Paper Id */
            paper_id: string;
            /** Approval */
            approval: {
                [key: string]: unknown;
            };
        };
        /** Body_post_artifact_binary_api_papers__paper_id__artifact__name__upload_post */
        Body_post_artifact_binary_api_papers__paper_id__artifact__name__upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_api_files_upload_post */
        Body_upload_api_files_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_paper_api_papers_post */
        Body_upload_paper_api_papers_post: {
            /** File */
            file: string;
        };
        /**
         * ConfigUpdateRequest
         * @description PUT /api/config body. Same shape as ConfigView for everything
         *     except secrets: secrets, when present, replace `secrets.env`.
         *
         *     The server validates the structure but does NOT call out to LLM/TTS
         *     — that's POST /api/config/validate's job.
         */
        ConfigUpdateRequest: {
            /** Paths */
            paths?: {
                [key: string]: string;
            } | null;
            /** Llm */
            llm?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** Tts */
            tts?: {
                [key: string]: unknown;
            } | null;
            /** Video */
            video?: {
                [key: string]: unknown;
            } | null;
            /** Slides */
            slides?: {
                [key: string]: unknown;
            } | null;
            /** Review */
            review?: {
                [key: string]: unknown;
            } | null;
            /** Scheduler */
            scheduler?: {
                [key: string]: unknown;
            } | null;
            /** Secrets */
            secrets?: {
                [key: string]: string;
            } | null;
        };
        /**
         * ConfigView
         * @description Sanitized config returned by GET /api/config.
         *
         *     Mirrors the shape of papercast.core.config.Config but redacts secrets:
         *         - llm.*.api_key → never serialized
         *         - llm.*.api_key_env → name only; *_set boolean indicates resolution
         *         - secrets fingerprint shows '****' suffix only
         */
        ConfigView: {
            /** Paths */
            paths: {
                [key: string]: string;
            };
            /** Llm */
            llm: {
                [key: string]: components["schemas"]["LLMTargetView"];
            };
            /** Tts */
            tts: {
                [key: string]: unknown;
            };
            /** Video */
            video: {
                [key: string]: unknown;
            };
            /** Slides */
            slides: {
                [key: string]: unknown;
            };
            /** Review */
            review: {
                [key: string]: unknown;
            };
            /** Scheduler */
            scheduler: {
                [key: string]: unknown;
            };
            /** Secrets Fingerprint */
            secrets_fingerprint: {
                [key: string]: string;
            };
        };
        /** CreateResponse */
        CreateResponse: {
            /** Paper Id */
            paper_id: string;
            /** Filename */
            filename: string;
            stage: components["schemas"]["Stage"];
            /**
             * Already Exists
             * @default false
             */
            already_exists: boolean;
        };
        /** DeleteRequest */
        DeleteRequest: {
            /** Root */
            root: string;
            /** Path */
            path: string;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** FileNode */
        FileNode: {
            /** Name */
            name: string;
            /** Rel Path */
            rel_path: string;
            /** Is Dir */
            is_dir: boolean;
            /** Size */
            size?: number | null;
            /** Mtime */
            mtime?: string | null;
            /** Children */
            children?: components["schemas"]["FileNode"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Config Summary */
            config_summary: {
                [key: string]: unknown;
            };
        };
        /**
         * LLMTargetView
         * @description Sanitized view of LLMTarget — never includes raw api_key.
         */
        LLMTargetView: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Api Key Env */
            api_key_env: string;
            /** Base Url */
            base_url?: string | null;
            /** Max Tokens */
            max_tokens: number;
            /** Temperature */
            temperature?: number | null;
            /** Timeout Sec */
            timeout_sec: number;
            /** Api Key Set */
            api_key_set: boolean;
        };
        /** PaperDetail */
        PaperDetail: {
            /** Paper Id */
            paper_id: string;
            /** Filename */
            filename: string;
            stage: components["schemas"]["Stage"];
            /** Ingested At */
            ingested_at: string;
            /** Published At */
            published_at?: string | null;
            /** Title */
            title?: string | null;
            /** Errors */
            errors?: string[];
            /** History */
            history?: components["schemas"]["PaperHistoryEntry"][];
            /** Artifacts */
            artifacts?: string[];
            /** Output Path */
            output_path?: string | null;
        };
        /** PaperHistoryEntry */
        PaperHistoryEntry: {
            stage: components["schemas"]["Stage"];
            /** Ts */
            ts: string;
        };
        /** PaperSummary */
        PaperSummary: {
            /** Paper Id */
            paper_id: string;
            /** Filename */
            filename: string;
            stage: components["schemas"]["Stage"];
            /** Ingested At */
            ingested_at: string;
            /** Published At */
            published_at?: string | null;
            /** Title */
            title?: string | null;
            /** Errors */
            errors?: string[];
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /**
             * Target
             * @enum {string}
             */
            target: "reading" | "slides_plan" | "script";
            /**
             * Items
             * @description Per-target shape:
             *       reading      → [{section, feedback}]
             *       slides_plan  → [{page_no, feedback}]
             *       script       → [{page_no, feedback}]
             */
            items?: {
                [key: string]: unknown;
            }[];
            /**
             * Feedback
             * @description Optional global feedback applied to all items in this batch.
             */
            feedback?: string | null;
            /**
             * Merge
             * @default true
             */
            merge: boolean;
        };
        /** RegenerateResponse */
        RegenerateResponse: {
            /** Paper Id */
            paper_id: string;
            /**
             * Target
             * @enum {string}
             */
            target: "reading" | "slides_plan" | "script";
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** RevealRequest */
        RevealRequest: {
            /** Root */
            root: string;
            /** Path */
            path: string;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "ingested" | "parsed" | "figures_split" | "read_done" | "slides_done" | "script_done" | "awaiting_review" | "approved" | "tts_submitted" | "tts_done" | "composed" | "published" | "failed";
        /** TextWriteRequest */
        TextWriteRequest: {
            /** Content */
            content: string;
        };
        /** TreeResponse */
        TreeResponse: {
            /** Root */
            root: string;
            /** Base Path */
            base_path: string;
            /** Nodes */
            nodes: components["schemas"]["FileNode"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_papers_api_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSummary"][];
                };
            };
        };
    };
    upload_paper_api_papers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_paper_api_papers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_paper_api_papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_inbox_route_api_papers_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"][];
                };
            };
        };
    };
    start_paper_api_papers__paper_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_paper_api_papers__paper_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_paper_api_papers__paper_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_artifacts_api_papers__paper_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_papers__paper_id__artifact__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_artifact_text_api_papers__paper_id__artifact__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_artifact_binary_api_papers__paper_id__artifact__name__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_artifact_binary_api_papers__paper_id__artifact__name__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roots_api_files_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    list_files_api_files_get: {
        parameters: {
            query: {
                /** @description one of: inbox, archive, work, review, output, template, template_meta, prompts, logs */
                root: string;
                /** @description relative path under the root */
                path?: string;
                /** @description recurse into subdirs (caps at 5000 entries) */
                recurse?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_path_api_files_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_files_download_get: {
        parameters: {
            query: {
                root: string;
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_files_upload_post: {
        parameters: {
            query: {
                /** @description one of: inbox */
                root: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_in_explorer_api_files_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_papers__paper_id__review_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_papers__paper_id__review_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_preview_api_papers__paper_id__review_regenerate_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
