/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        /**
         * Put Config
         * @description Persist changes and refresh the in-memory Config.
         *
         *     Body shape mirrors GET; any field omitted is left untouched.
         *     Including `secrets` (dict[str, str]) writes those KEY=VALUE pairs
         *     to config/secrets.env and updates os.environ for the live process.
         */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Round-trip `complete('ping')` against each LLM endpoint and
         *     return per-role status (ok/detail). Costs at most a tiny number of
         *     tokens per role.
         */
        post: operations["validate_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_papers_get"];
        put?: never;
        /**
         * Upload Paper
         * @description Accept a PDF upload, register it, return the new paper_id.
         *
         *     Mirrors `papercast scan` for one file: stream to inbox, hash, copy
         *     into work/<pid>/source.pdf, insert DB row, move original to archive.
         */
        post: operations["upload_paper_api_papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Paper
         * @description Hard delete: drop work/<pid>/, review/<pid>/, and the DB row.
         *
         *     output/<filename>.mp4 is intentionally NOT removed — that's the
         *     final deliverable and the user may still want it.
         */
        delete: operations["delete_paper_api_papers__paper_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Inbox Route
         * @description Trigger a full inbox scan (covers PDFs already on disk before the
         *     server started). Equivalent to `papercast scan`.
         */
        post: operations["scan_inbox_route_api_papers_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Paper
         * @description Kick off the JobOrchestrator for this paper.
         *
         *     Optional body collects reviewer-supplied Cover values (`report_date`,
         *     `reviewer`, `major`). They're persisted to
         *     `review/<pid>/start_meta.json` so the planner runner can include
         *     them in its prompt and the approval step can re-bake the .pptx
         *     without re-running the LLM.
         */
        post: operations["start_paper_api_papers__paper_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Paper */
        post: operations["stop_paper_api_papers__paper_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Paper
         * @description If the paper is in `failed`, walk back to its previous successful
         *     stage. Mirrors `papercast retry-failed` for one paper.
         */
        post: operations["retry_paper_api_papers__paper_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/preview-render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Render
         * @description Render the assembled .pptx into PNGs for the Review tab.
         *
         *     Idempotent — if `work/<pid>/slides_png/` already has files, those
         *     are returned. Otherwise LibreOffice runs once (~30s on first call)
         *     and the result is cached on disk.
         *
         *     The route is intentionally separate from the `composed` stage:
         *     that one renders at a higher DPI for video, and only after
         *     approval. This one runs at 100 DPI for thumbnails and lets the
         *     reviewer see the deck before approving.
         */
        post: operations["preview_render_api_papers__paper_id__preview_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/figures/{figure_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Figure Route
         * @description Re-extract a single figure with the current caption detector.
         *
         *     Useful after a fix lands (e.g. tightened table-caption regex) so
         *     the user can refresh one image without redoing figures_split.
         */
        post: operations["rerun_figure_route_api_papers__paper_id__figures__figure_id__rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/figures/{figure_id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Figure Route
         * @description Overwrite a figure's PNG bytes with an uploaded file.
         *
         *     The figures.json metadata (filename / bbox / caption) is preserved
         *     — only the image bytes change. Accepts PNG / JPG / WebP; the
         *     extension on disk stays whatever figures.json declared.
         */
        post: operations["replace_figure_route_api_papers__paper_id__figures__figure_id__replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Paper Events
         * @description Replay the per-paper history as a list of WebSocket-shaped events.
         *
         *     Used by the WebUI when entering a detail page: render a baseline
         *     timeline before the live `/ws/papers/{pid}` stream takes over. Each
         *     successful Stage transition becomes one `stage_advanced` event;
         *     error messages become `failed` events at the FAILED transition.
         */
        get: operations["list_paper_events_api_papers__paper_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Paper Artifacts
         * @description List logical artifact names that exist on disk for this paper.
         */
        get: operations["list_paper_artifacts_api_papers__paper_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/artifact/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Stream a binary artifact, or wrap a text artifact in JSON.
         *
         *     Returns:
         *         - FileResponse for binary types (.pdf, .pptx, .mp4, .png, .mp3)
         *         - TextArtifactResponse for textual types (.json, .md, ...)
         */
        get: operations["get_artifact_api_papers__paper_id__artifact__name__get"];
        /**
         * Put Artifact Text
         * @description Overwrite a text artifact with the request body.
         *
         *     Only artifacts in WRITABLE_ARTIFACTS are accepted; everything else
         *     is read-only via this endpoint. Binary replacements go through
         *     POST /artifact/{name}/upload.
         */
        put: operations["put_artifact_text_api_papers__paper_id__artifact__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/artifact/{name}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Artifact Binary
         * @description Replace a binary artifact (currently: pptx). Reviewer downloads
         *     the auto-generated .pptx, edits in PowerPoint, drops the new file
         *     here to overwrite.
         */
        post: operations["post_artifact_binary_api_papers__paper_id__artifact__name__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Roots
         * @description Listable root names. Tight by design — see PUBLIC_LIST_ROOTS.
         */
        get: operations["list_roots_api_files_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_files_get"];
        put?: never;
        post?: never;
        /** Delete Path */
        delete: operations["delete_path_api_files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Download a single file. Permissive by design — the Review tab's
         *     figure thumbnails and the FilesPage cards both call this with paths
         *     the server itself emitted. `safe_resolve` keeps the path inside the
         *     declared root, so traversal attempts (`../../foo`) still 403.
         */
        get: operations["download_file_api_files_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description General-purpose upload to a whitelisted root.
         *
         *     Currently restricted to `inbox` to avoid polluting work/review/output
         *     with arbitrary user files. The proper way to insert a paper is via
         *     POST /api/papers (which calls inbox upload + scan internally), but
         *     this endpoint is handy for batch ingest.
         */
        post: operations["upload_api_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal In Explorer
         * @description Open the OS file manager focused on the file. Best-effort —
         *     headless servers / different desktop environments may no-op.
         */
        post: operations["reveal_in_explorer_api_files_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Paper Files
         * @description One entry per paper, listing the user-facing deliverables.
         *
         *     For each paper we surface (when present):
         *       - source_pdf  in archive/    : the original upload
         *       - deck_pptx   in review/<pid>: the assembled deck after script_done
         *       - video_mp4   in output/     : the final published video
         *
         *     Pipeline-internal artifacts (work/<pid>/{reading,slides_plan,script}.json,
         *     figures, audio chunks, voicer_tasks, ...) are NOT exposed here —
         *     they're available via the per-paper artifact API used by the Review
         *     tab, but a casual user shouldn't be wading through them.
         */
        get: operations["list_paper_files_api_files_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_papers__paper_id__review_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_papers__paper_id__review_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/regenerate/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Preview
         * @description Render the LLM prompt that *would* be sent for this regenerate
         *     request, without actually calling the LLM. Useful for the WebUI to
         *     let the reviewer eyeball / tweak the request before spending tokens.
         */
        post: operations["regenerate_preview_api_papers__paper_id__review_regenerate_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/refresh-from-disk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh From Disk Route
         * @description Re-read on-disk artifacts and re-render slide thumbnails.
         *
         *     Use case: the reviewer downloaded the .pptx, edited it in PowerPoint,
         *     saved it back into ``work/<pid>/<pid>.pptx`` (and possibly tweaked
         *     ``script.md``), and now wants the Review tab to reflect those edits.
         *
         *     Side effect: writes ``review/<pid>/manual_override.json`` so the
         *     subsequent ``apply_approval`` call publishes the user-edited deck
         *     instead of re-assembling it from the template.
         *
         *     Returns the new slide PNG list + mtimes for cache-busting on the
         *     client.
         */
        post: operations["refresh_from_disk_route_api_papers__paper_id__review_refresh_from_disk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Route
         * @description Re-assemble work/<pid>/<pid>.pptx from slides_plan.json + script.md
         *     and re-render the preview thumbnails.
         *
         *     Use case: the reviewer edited a page's JSON or script via the WebUI's
         *     PageEditDialog. Those PUTs only touched the JSON / Markdown — the
         *     .pptx and its PNG thumbnails still reflect the prior version. This
         *     route brings them back into sync.
         *
         *     Refuses with 409 (detail starts with "manual_override:") when the
         *     paper has manual_override set, unless ``force=true``. The override
         *     indicates the user previously hand-edited the .pptx in PowerPoint;
         *     rebuilding from JSON would silently discard those edits.
         */
        post: operations["rebuild_route_api_papers__paper_id__review_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}/review/recut-figures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recut Figures Route
         * @description Re-run figures_split end-to-end and refresh figures.json.
         *
         *     Use case: the reviewer is unhappy with the auto-extracted figure
         *     crops (wrong bbox, missing figure, bad caption match). Per-figure
         *     rerun (POST /papers/{pid}/figures/{fid}/rerun) handles single
         *     fixes; this is the whole-set version, useful when the underlying
         *     detector / extractor mode was tweaked.
         *
         *     Side effects:
         *       - figures.json is backed up to .history/ before being rewritten
         *       - orphan figure_*.png files (no longer in the new figures.json)
         *         are removed; paper_first_page.png is preserved
         *       - slides_plan.json is scanned for image_id / figure_id refs that
         *         no longer resolve — surfaced via `referenced_missing` so the
         *         WebUI can prompt the user to fix the plan.
         *
         *     Returns the new figure count + the list of orphan files removed +
         *     pages whose plan still references missing ids.
         */
        post: operations["recut_figures_route_api_papers__paper_id__review_recut_figures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_api_voice_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone
         * @description Multipart: file (audio sample) + voice_id + optional label/prompt_text.
         *
         *     Steps:
         *       1. Validate voice_id format and uniqueness in voices.json
         *       2. Upload the audio bytes to MiniMax (purpose=voice_clone)
         *       3. Register the cloned voice
         *       4. Append to local voices.json
         */
        post: operations["clone_api_voice_clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Synchronous T2A — returns mp3 bytes the browser can `<audio>`-play.
         *
         *     Reads up to 200 chars; truncated server-side too in
         *     `papercast.voicer.clone.preview_voice`.
         */
        post: operations["preview_api_voice_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/{voice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Voice
         * @description Remove a voice from local voices.json. The cloud voice on
         *     MiniMax stays — re-importing the same voice_id later is the
         *     recommended path for full removal.
         */
        delete: operations["delete_voice_api_voice__voice_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/{voice_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Favorite
         * @description Mark a voice as favorited / unfavorited.
         *
         *     Behavior:
         *       - If `voice_id` is already in voices.json (typically a cloned
         *         voice), update its `is_favorite` flag in place.
         *       - Otherwise (a system voice the user wants to favorite), append a
         *         new record with `source="system"` and the supplied label, so
         *         future renders don't need to look the label up again.
         *       - Setting `is_favorite=False` on a system voice removes its
         *         record entirely (we don't keep "unfavorited" stubs around).
         */
        post: operations["set_favorite_api_voice__voice_id__favorite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Script
         * @description Use the Author LLM to draft a ~1000-char academic-talk sample for
         *     voice cloning. The user supplies research keywords; the model
         *     fabricates a plausible related paper and writes the talk.
         *
         *     Costs ~4K tokens of the Author provider's quota per call.
         */
        post: operations["generate_script_api_voice_script_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Report Date
             * @description Date string substituted into Cover's {{REPORT_DATE}}; any format the lab template accepts (e.g. '2026年5月17日').
             */
            report_date?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /**
             * Voice
             * @description MiniMax voice_id (overrides config tts.voice for this paper).
             */
            voice?: string | null;
            /** Overrides */
            overrides?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Paper Id */
            paper_id: string;
            /** Approval */
            approval: {
                [key: string]: unknown;
            };
        };
        /** Body_clone_api_voice_clone_post */
        Body_clone_api_voice_clone_post: {
            /** Voice Id */
            voice_id: string;
            /** Label */
            label?: string | null;
            /** Prompt Text */
            prompt_text?: string | null;
            /**
             * Model
             * @default speech-2.6-hd
             */
            model: string;
            /** File */
            file: string;
        };
        /** Body_post_artifact_binary_api_papers__paper_id__artifact__name__upload_post */
        Body_post_artifact_binary_api_papers__paper_id__artifact__name__upload_post: {
            /** File */
            file: string;
        };
        /** Body_replace_figure_route_api_papers__paper_id__figures__figure_id__replace_post */
        Body_replace_figure_route_api_papers__paper_id__figures__figure_id__replace_post: {
            /** File */
            file: string;
        };
        /** Body_upload_api_files_upload_post */
        Body_upload_api_files_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_paper_api_papers_post */
        Body_upload_paper_api_papers_post: {
            /** File */
            file: string;
        };
        /** CloneResponse */
        CloneResponse: {
            /** Voice Id */
            voice_id: string;
            /** File Id */
            file_id: number;
            /** Label */
            label: string | null;
            /** Created At */
            created_at: string;
            /** Model */
            model: string;
        };
        /**
         * ConfigUpdateRequest
         * @description PUT /api/config body. Same shape as ConfigView for everything
         *     except secrets: secrets, when present, replace `secrets.env`.
         *
         *     The server validates the structure but does NOT call out to LLM/TTS
         *     — that's POST /api/config/validate's job.
         */
        ConfigUpdateRequest: {
            /** Paths */
            paths?: {
                [key: string]: string;
            } | null;
            /** Llm */
            llm?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** Tts */
            tts?: {
                [key: string]: unknown;
            } | null;
            /** Video */
            video?: {
                [key: string]: unknown;
            } | null;
            /** Slides */
            slides?: {
                [key: string]: unknown;
            } | null;
            /** Review */
            review?: {
                [key: string]: unknown;
            } | null;
            /** Scheduler */
            scheduler?: {
                [key: string]: unknown;
            } | null;
            /** Secrets */
            secrets?: {
                [key: string]: string;
            } | null;
        };
        /**
         * ConfigView
         * @description Sanitized config returned by GET /api/config.
         *
         *     Mirrors the shape of papercast.core.config.Config but redacts secrets:
         *         - llm.*.api_key → never serialized
         *         - llm.*.api_key_env → name only; *_set boolean indicates resolution
         *         - secrets fingerprint shows '****' suffix only
         */
        ConfigView: {
            /** Paths */
            paths: {
                [key: string]: string;
            };
            /** Llm */
            llm: {
                [key: string]: components["schemas"]["LLMTargetView"];
            };
            /** Tts */
            tts: {
                [key: string]: unknown;
            };
            /** Video */
            video: {
                [key: string]: unknown;
            };
            /** Slides */
            slides: {
                [key: string]: unknown;
            };
            /** Review */
            review: {
                [key: string]: unknown;
            };
            /** Scheduler */
            scheduler: {
                [key: string]: unknown;
            };
            /** Secrets Fingerprint */
            secrets_fingerprint: {
                [key: string]: string;
            };
        };
        /** CreateResponse */
        CreateResponse: {
            /** Paper Id */
            paper_id: string;
            /** Filename */
            filename: string;
            stage: components["schemas"]["Stage"];
            /**
             * Already Exists
             * @default false
             */
            already_exists: boolean;
        };
        /** DeleteRequest */
        DeleteRequest: {
            /** Root */
            root: string;
            /** Path */
            path: string;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * FavoriteRequest
         * @description POST /api/voice/{voice_id}/favorite — toggle favorite state.
         *
         *     For system voices that aren't yet in voices.json, supply `label`
         *     so we can render them later without re-fetching the public catalog.
         */
        FavoriteRequest: {
            /** Is Favorite */
            is_favorite: boolean;
            /** Label */
            label?: string | null;
            /**
             * Source
             * @default system
             */
            source: string;
        };
        /** FileNode */
        FileNode: {
            /** Name */
            name: string;
            /** Rel Path */
            rel_path: string;
            /** Is Dir */
            is_dir: boolean;
            /** Size */
            size?: number | null;
            /** Mtime */
            mtime?: string | null;
            /** Children */
            children?: components["schemas"]["FileNode"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Config Summary */
            config_summary: {
                [key: string]: unknown;
            };
        };
        /**
         * LLMTargetView
         * @description Sanitized view of LLMTarget — never includes raw api_key.
         */
        LLMTargetView: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Api Key Env */
            api_key_env: string;
            /** Base Url */
            base_url?: string | null;
            /** Max Tokens */
            max_tokens: number;
            /** Temperature */
            temperature?: number | null;
            /** Timeout Sec */
            timeout_sec: number;
            /** Api Key Set */
            api_key_set: boolean;
        };
        /** PaperDetail */
        PaperDetail: {
            /** Paper Id */
            paper_id: string;
            /** Filename */
            filename: string;
            stage: components["schemas"]["Stage"];
            /** Ingested At */
            ingested_at: string;
            /** Published At */
            published_at?: string | null;
            /** Title */
            title?: string | null;
            /** Errors */
            errors?: string[];
            /** History */
            history?: components["schemas"]["PaperHistoryEntry"][];
            /** Artifacts */
            artifacts?: string[];
            /** Output Path */
            output_path?: string | null;
        };
        /** PaperFileEntry */
        PaperFileEntry: {
            /** Kind */
            kind: string;
            /** Root */
            root: string;
            /** Path */
            path: string;
            /** Filename */
            filename: string;
            /** Size */
            size?: number | null;
            /** Mtime */
            mtime?: string | null;
        };
        /** PaperFiles */
        PaperFiles: {
            /** Paper Id */
            paper_id: string;
            /** Title */
            title?: string | null;
            /** Filename */
            filename: string;
            /** Stage */
            stage: string;
            /** Ingested At */
            ingested_at: string;
            /** Report Date */
            report_date?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["PaperFileEntry"][];
        };
        /** PaperHistoryEntry */
        PaperHistoryEntry: {
            stage: components["schemas"]["Stage"];
            /** Ts */
            ts: string;
        };
        /** PaperSummary */
        PaperSummary: {
            /** Paper Id */
            paper_id: string;
            /** Filename */
            filename: string;
            stage: components["schemas"]["Stage"];
            /** Ingested At */
            ingested_at: string;
            /** Published At */
            published_at?: string | null;
            /** Title */
            title?: string | null;
            /** Errors */
            errors?: string[];
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Text */
            text: string;
            /** Voice Id */
            voice_id: string;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Model
             * @default speech-2.6-hd
             */
            model: string;
        };
        /** RebuildRequest */
        RebuildRequest: {
            /**
             * Force
             * @description When manual_override is set, rebuild would overwrite the user's hand-edited .pptx. Pass force=true to proceed anyway (the WebUI surfaces a confirm dialog before re-submitting with this flag).
             * @default false
             */
            force: boolean;
        };
        /** RebuildResponse */
        RebuildResponse: {
            /** Paper Id */
            paper_id: string;
            /** Slides */
            slides: {
                [key: string]: unknown;
            }[];
            /** Manual Override Cleared */
            manual_override_cleared: boolean;
            /** Mtimes */
            mtimes: {
                [key: string]: string | null;
            };
        };
        /** RecutFiguresRequest */
        RecutFiguresRequest: {
            /**
             * Mode
             * @description Optional override for the figure-extraction mode. One of 'text_blocks' or 'visual_cluster'; None uses the config default (cfg.slides.figure_extractor).
             */
            mode?: string | null;
        };
        /** RecutFiguresResponse */
        RecutFiguresResponse: {
            /** Paper Id */
            paper_id: string;
            /** Figures Count */
            figures_count: number;
            /** Mode */
            mode: string | null;
            /** Removed Orphans */
            removed_orphans: string[];
            /** Referenced Missing */
            referenced_missing: {
                [key: string]: unknown;
            }[];
            /** Backup */
            backup: string | null;
        };
        /** RefreshFromDiskResponse */
        RefreshFromDiskResponse: {
            /** Paper Id */
            paper_id: string;
            /** Slides */
            slides: {
                [key: string]: unknown;
            }[];
            /** Manual Override */
            manual_override: {
                [key: string]: unknown;
            };
            /** Mtimes */
            mtimes: {
                [key: string]: string | null;
            };
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /**
             * Target
             * @enum {string}
             */
            target: "reading" | "slides_plan" | "script";
            /**
             * Items
             * @description Per-target shape:
             *       reading      → [{section, feedback}]
             *       slides_plan  → [{page_no, feedback}]
             *       script       → [{page_no, feedback}]
             */
            items?: {
                [key: string]: unknown;
            }[];
            /**
             * Feedback
             * @description Optional global feedback applied to all items in this batch.
             */
            feedback?: string | null;
            /**
             * Merge
             * @default true
             */
            merge: boolean;
        };
        /** RegenerateResponse */
        RegenerateResponse: {
            /** Paper Id */
            paper_id: string;
            /**
             * Target
             * @enum {string}
             */
            target: "reading" | "slides_plan" | "script";
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** RevealRequest */
        RevealRequest: {
            /** Root */
            root: string;
            /** Path */
            path: string;
        };
        /**
         * ScriptRequest
         * @description POST /api/voice/script — generate a ~1000-char clone sample.
         */
        ScriptRequest: {
            /** Keywords */
            keywords: string[];
        };
        /** ScriptResponse */
        ScriptResponse: {
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "ingested" | "parsed" | "figures_split" | "read_done" | "slides_done" | "script_done" | "awaiting_review" | "approved" | "tts_submitted" | "tts_done" | "composed" | "published" | "failed";
        /** StartPaperRequest */
        StartPaperRequest: {
            /** Report Date */
            report_date?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Major */
            major?: string | null;
        };
        /** TextWriteRequest */
        TextWriteRequest: {
            /** Content */
            content: string;
        };
        /** TreeResponse */
        TreeResponse: {
            /** Root */
            root: string;
            /** Base Path */
            base_path: string;
            /** Nodes */
            nodes: components["schemas"]["FileNode"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceRecord */
        VoiceRecord: {
            /** Voice Id */
            voice_id: string;
            /** Label */
            label?: string | null;
            /** Created At */
            created_at: string;
            /** Source File Id */
            source_file_id?: number | null;
            /** Prompt Text */
            prompt_text?: string | null;
            /**
             * Model
             * @default speech-2.6-hd
             */
            model: string;
            /**
             * Is Favorite
             * @default true
             */
            is_favorite: boolean;
            /**
             * Source
             * @default cloned
             */
            source: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_papers_api_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSummary"][];
                };
            };
        };
    };
    upload_paper_api_papers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_paper_api_papers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_paper_api_papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_inbox_route_api_papers_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResponse"][];
                };
            };
        };
    };
    start_paper_api_papers__paper_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartPaperRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_paper_api_papers__paper_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_paper_api_papers__paper_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_render_api_papers__paper_id__preview_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_figure_route_api_papers__paper_id__figures__figure_id__rerun_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                figure_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_figure_route_api_papers__paper_id__figures__figure_id__replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                figure_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_figure_route_api_papers__paper_id__figures__figure_id__replace_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_events_api_papers__paper_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_artifacts_api_papers__paper_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_papers__paper_id__artifact__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_artifact_text_api_papers__paper_id__artifact__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_artifact_binary_api_papers__paper_id__artifact__name__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_artifact_binary_api_papers__paper_id__artifact__name__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roots_api_files_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    list_files_api_files_get: {
        parameters: {
            query: {
                /** @description one of: output, archive */
                root: string;
                /** @description relative path under the root */
                path?: string;
                /** @description recurse into subdirs (caps at 5000 entries) */
                recurse?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_path_api_files_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_files_download_get: {
        parameters: {
            query: {
                root: string;
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_files_upload_post: {
        parameters: {
            query: {
                /** @description one of: inbox */
                root: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_in_explorer_api_files_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_files_api_files_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperFiles"][];
                };
            };
        };
    };
    approve_api_papers__paper_id__review_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_papers__paper_id__review_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_preview_api_papers__paper_id__review_regenerate_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_from_disk_route_api_papers__paper_id__review_refresh_from_disk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshFromDiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_route_api_papers__paper_id__review_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebuildResponse"];
                };
            };
            /** @description slides_plan.json/script.md missing, OR manual_override is set and force=false. The error detail starts with 'manual_override:' for the override-conflict case so the WebUI can distinguish it from a missing-artifact 409. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recut_figures_route_api_papers__paper_id__review_recut_figures_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecutFiguresRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecutFiguresResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_api_voice_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceRecord"][];
                };
            };
        };
    };
    clone_api_voice_clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_clone_api_voice_clone_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_voice_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_voice_api_voice__voice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_favorite_api_voice__voice_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_script_api_voice_script_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
